spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zoom
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect